name: life_app
description: Diary and Relaxation App.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # State management
  flutter_hooks: ^0.18.4
  hooks_riverpod: ^1.0.4

  # Routing
  auto_route: ^4.0.1

  # Localization
  easy_localization: ^3.0.1

  # Data class
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0

  # Cloud
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  firebase_analytics: ^9.1.9
  firebase_crashlytics: ^2.8.1
  supabase_flutter: ^0.3.1+1
  supabase: ^0.3.4+1
  google_sign_in: ^5.3.3

  # Layout
  flutter_screenutil: ^5.5.3+2

  # Fonts
  google_fonts: ^3.0.1

  # Picture
  flutter_svg: ^1.1.0

  # Perks
  flutter_easyloading: ^3.0.5

  # Local Storage
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  logger: ^1.1.0

  cool_alert: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Code Generators
  build_runner: ^2.1.11
  auto_route_generator: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
